export enum RESPONSE_CODE {
  OK = 1,
  CLIENT_ERROR = 2,
  SERVER_ERROR = 3,
  METHOD_NOT_ALLOWED = 4,
  TOKEN_MISMATCH = 5,
  NOT_FOUND = 6,
  UNAUTHORIZED = 7,
  UNAUTHENTICATED = 8,
  INVALID_CONTENT = 9,
  INVALID_CREDENTIALS = 10
}
